name: "AirPlay 2 for Home Assistant"
description: "AirPlay 2 receiver using shairport-sync (ALSA + MQTT)"
version: "dev"
slug: "airplay2"
init: false

arch:
  - armv7
  - aarch64

boot: auto
host_network: true
audio: true

options:
  airplay_name: "Home Assistant AirPlay"
  alsa_device: "hw:0,0"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "shairport-sync"

schema:
  airplay_name: str
  alsa_device: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: password?
  mqtt_topic: str

image: "ghcr.io/tingletangle443/airplay2-{arch}"
